version: "3.8"

services:
    client:
        image: nginx:latest
        container_name: client
        ports:
            - 80:80
        volumes:            
            - ./default.conf.template:/etc/nginx/templates/default.conf.template
            - ./src/Game.Client:/data/www
        environment:
            - SERVER_HOST=server
            - SERVER_PORT=80

    server:
        image: aaronshiels/gameapi:server
        container_name: server
        expose:
            - 80