version: "3.8"

services:
    proxy:
        image: nginx:latest
        container_name: client
        ports:
            - 80:80
        volumes:
            - ./default.conf.template:/etc/nginx/templates/default.conf.template
            - ./src/Game.Client:/data/www
        environment:
            - API_HOST=api
            - API_PORT=80

    api:
        image: aaronshiels/game:api
        container_name: api
        expose:
            - 80
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=http://+:80
