version: "3.8"

services:
    proxy:
        image: aaronshiels/game:proxy
        container_name: proxy
        ports:
            - 80:80
        environment:
            - API_HOST=api
            - API_PORT=5000

    api:
        image: aaronshiels/game:api
        container_name: api
        expose:
            - 5000
        environment: 
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=http://+:5000