version: "3.8"

services:
    proxy:
        image: nginx:latest
        container_name: proxy
        ports:
            - 80:80
        volumes:
            - ./default.conf.template:/etc/nginx/templates/default.conf.template
        environment:
            - API_HOST=api
            - API_PORT=80
            - CLIENT_HOST=client
            - CLIENT_PORT=80

    client:
        image: aaronshiels/game:client
        container_name: client
        expose:
            - 80

    api:
        image: aaronshiels/game:api
        container_name: api
        expose:
            - 80
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=http://+:80
